artifact_location: /Users/diogoogaspar/Documents/Universidade/3Ano/2SEMESTRE/AOOP/TRAB-DETECTION-MATRICULAS/license-plate-recognition/models/License
  Plate Recognition.v11i.yolov11/runs/mlflow/789099971470877312
creation_time: 1748678138565
experiment_id: '789099971470877312'
last_update_time: 1748678138565
lifecycle_stage: active
name: /Shared/Ultralytics
