artifact_location: /Users/diogoogaspar/Documents/Universidade/3Ano/2SEMESTRE/AOOP/TRAB-DETECTION-MATRICULAS/license-plate-recognition/models/License
  Plate Recognition.v11i.yolov11/runs/mlflow/0
creation_time: 1748678138556
experiment_id: '0'
last_update_time: 1748678138556
lifecycle_stage: active
name: Default
