artifact_uri: /Users/diogoogaspar/Documents/Universidade/3Ano/2SEMESTRE/AOOP/TRAB-DETECTION-MATRICULAS/license-plate-recognition/models/License
  Plate Recognition.v11i.yolov11/runs/mlflow/789099971470877312/660978496264406b9cbe76b21abef602/artifacts
end_time: 1748765323697
entry_point_name: ''
experiment_id: '789099971470877312'
lifecycle_stage: active
run_id: 660978496264406b9cbe76b21abef602
run_name: matriculas-modelo5
run_uuid: 660978496264406b9cbe76b21abef602
source_name: ''
source_type: 4
source_version: ''
start_time: 1748678139382
status: 3
tags: []
user_id: diogoogaspar
